### ISSUE TITLE
Python errors while  running

### ISSUE THREAD

**Issue by superuser789** [swing-research/scatsense#1]
Running using Python3 on windows10 64bit.
Directly running :: `python exp.py configs/lego1_fspeech_1.txt`
Shows this error :: 
```
Traceback (most recent call last):
  File "exp.py", line 120, in <module>
    src_ind = np.random.choice(L[0], J, replace=False) #pick speaker(s)
  File "mtrand.pyx", line 1120, in mtrand.RandomState.choice
ValueError: a must be greater than 0
```

Running :: `python exp_white.py configs/lego1_10deg_white_1.txt`
Shows this error :: 
```
Traceback (most recent call last):
  File "exp_white.py", line 106, in <module>
    y = stft(yt, Fn)[f0:, :] #spectrogram of recorded signal
  File "D:\Speech\git\scatsense-master\core\signal.py", line 20, in stft
    x = np.hstack((np.zeros((nhop,)),x,np.zeros((zero_pad,)))) #zero padding at the beginning to avoid boundary effects
TypeError: 'numpy.float64' object cannot be interpreted as an integer
```

While running using  Python 2.7 on windows10 64 bit

 :: `python exp_white.py configs/lego1_10deg_white_1.txt`
Shows this error ::
```
Traceback (most recent call last):
  File "exp_white.py", line 106, in <module>
    y = stft(yt, Fn)[f0:, :] #spectrogram of recorded signal
  File "D:\Speech\git\scatsense-master\core\signal.py", line 20, in stft
    x = np.hstack(int(np.zeros((nhop,))),x,int(np.zeros((zero_pad,)))) #zero padding at the beginning to avoid boundary effects
TypeError: only size-1 arrays can be converted to Python scalars 
```

Please tell me how to fix this. 
I am trying to understand the method from your paper.

Thanks.

**Comment by dalia012** [comment]
Hello there,

Thanks for your interest in my work.

The first error (with exp.py) is due to the fact that the “test” folder containing the test files is empty. So the test data comes from the TIMIT dataset which I don’t have the rights to upload. Please obtain a copy or perhaps use other test files if you simply want to run the algorithm. I will update the code and documentation to make it clear.

For the second error (with exp_white.py), it seems you added an “int()” which is the source of the error. Please run the original code using Python 2.7.

Hope that helps!
